//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatixGameForm.MatixSharedGameServices
{
    using System.Runtime.Serialization;
    using System;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://www.xblip.com", ConfigurationName = "MatixGameForm.MatixSharedGameServices.IPingable")]
    public interface IPingable
    {

        [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://www.xblip.com/IPingable/Ping")]
        void Ping();
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IPingableChannel : IPingable, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class PingableClient : System.ServiceModel.ClientBase<IPingable>, IPingable
    {

        public PingableClient()
        {
        }

        public PingableClient(string endpointConfigurationName)
            :
                base(endpointConfigurationName)
        {
        }

        public PingableClient(string endpointConfigurationName, string remoteAddress)
            :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public PingableClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress)
            :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public PingableClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress)
            :
                base(binding, remoteAddress)
        {
        }

        public void Ping()
        {
            base.Channel.Ping();
        }
    }
}